apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: back
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: gcr.io/rampup21/movie-analyst-api
        ports:
        - containerPort: 80
