apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front
spec:
  selector:
    app: front
  type: NodePort
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 32132
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: gcr.io/rampup21/movie-analyst-ui:latest
        ports:
        - containerPort: 3030
          protocol: TCP